### ISSUE TITLE
在windows10用单张3070GPU运行看不到输出的训练记录，也没有抛出bug

### ISSUE THREAD

**Issue by Henry-Avery** [xyanchen/WiFi-CSI-Sensing-Benchmark#3]
PS D:\Learncode\RFresearch\WiFi-CSI-Sensing-Benchmark-main> python run.py --model MLP --dataset Widar
using dataset: Widar
using model: MLP
只输出了选择的模型和数据集，尝试了其他的也没有开始训练，是不是一定要在linux环境下呢？

**Comment by Henry-Avery** [comment]
这是终止后的Traceback：

> Traceback (most recent call last):
  File "D:\Learncode\RFresearch\WiFi-CSI-Sensing-Benchmark-main\run.py", line 92, in <module>
    if __name__ == "__main__":
  File "D:\Learncode\RFresearch\WiFi-CSI-Sensing-Benchmark-main\run.py", line 74, in main

    for data in tensor_loader:
  File "D:\Users\84909\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 628, in __next__       
    data = self._next_data()
  File "D:\Users\84909\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 671, in _next_data     
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "D:\Users\84909\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Users\84909\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 58, in <listcomp>    
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\Learncode\RFresearch\WiFi-CSI-Sensing-Benchmark-main\dataset.py", line 88, in __getitem__
    x = np.genfromtxt(sample_dir, delimiter=',')
  File "D:\Users\84909\anaconda3\lib\site-packages\numpy\lib\npyio.py", line 1997, in genfromtxt
    converters = [StringConverter(dtype, locked=True,
  File "D:\Users\84909\anaconda3\lib\site-packages\numpy\lib\npyio.py", line 1997, in <listcomp>
    converters = [StringConverter(dtype, locked=True,
KeyboardInterrupt

**Comment by Henry-Avery** [comment]
经过漫长的等待后，出现了很奇怪的结果，我大受震撼，而且虽然GPU显示有启动进程，但是占用率一直很低，磁盘读取倒是一直在20M/s，请问Windows系统可能需要改动那些地方呢？
PS D:\Learncode\RFresearch\WiFi-CSI-Sensing-Benchmark-main> python run.py --model MLP --dataset Widar
using dataset: Widar
using model: MLP
Epoch:1, Accuracy:0.9982,Loss:0.006224212
Epoch:2, Accuracy:1.0000,Loss:0.000000000

**Comment by zkzzhou** [comment]
> Traceback

是的 我也是这样 请问解决了嘛

**Comment by Henry-Avery** [comment]
> > Traceback
> 
> 是的 我也是这样 请问解决了嘛

就是慢，要等训练完一个epoch才会有记录，但是结果也很怪，怀疑没有正确读入数据

**Comment by xyanchen** [comment]
Long training time for an epoch is because Widar dataset is segmented into 546 batches and the approximate training time for an epoch is 3 minutes (with single RTX4090). If you want to visualize the training process, you could add _tqdm_ to _run.py_.

Because our code are written under Linux system, when extracting the category of a data, we split the address with '/'. But in Windows system, you need to change the forward slash to the double backslash in order to extract correct label for each data sample (in _dataset.py_):
e.g.
y = self.category[sample_dir.split('/')[-2]] 
to
y = self.category[sample_dir.split('\\')[-2]]

**Comment by Marsrocky** [comment]
> PS D:\Learncode\RFresearch\WiFi-CSI-Sensing-Benchmark-main> python run.py --model MLP --dataset Widar using dataset: Widar using model: MLP 只输出了选择的模型和数据集，尝试了其他的也没有开始训练，是不是一定要在linux环境下呢？

**Comment by Marsrocky** [comment]
> PS D:\Learncode\RFresearch\WiFi-CSI-Sensing-Benchmark-main> python run.py --model MLP --dataset Widar using dataset: Widar using model: MLP 只输出了选择的模型和数据集，尝试了其他的也没有开始训练，是不是一定要在linux环境下呢？

整套代码是基于Linux书写和测试的，Pytorch等各种环境的版本必须按照我们给出的去配置，每个版本的Pytorch、numpy、torchvision等都有很多不同，版本不对时会有很多令人无法理解的bug，也无法debug。
